#!/bin/bash

function createTally() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/tally.tallysolutions.com/

  export FABRIC_CA_CLIENT_HOME=${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname tally --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-tally.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-tally.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-tally.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-tally.pem
    OrganizationalUnitIdentifier: orderer' > "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy tally's CA cert to tally's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/tlscacerts"
  cp "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/tlscacerts/ca.crt"

  # Copy tally's CA cert to tally's /tlsca directory (for use by clients)
  mkdir -p "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/tlsca"
  cp "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/tlsca/tlsca.tally.tallysolutions.com-cert.pem"

  # Copy tally's CA cert to tally's /ca directory (for use by clients)
  mkdir -p "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/ca"
  cp "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/ca/ca.tally.tallysolutions.com-cert.pem"

  infoln "Registering tbchlfdevpeer01 "
  set -x
  fabric-ca-client register --caname tally --id.name tbchlfdevpeer01 --id.secret tbchlfdevpeer01pw --id.type peer --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname tally --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname tally --id.name tallyadmin --id.secret tallyadminpw --id.type admin --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the tbchlfdevpeer01 msp"
  set -x
  fabric-ca-client enroll -u https://tbchlfdevpeer01:tbchlfdevpeer01pw@localhost:7054 --caname tally -M "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.commsp" --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/config.yaml" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.commsp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://tbchlfdevpeer01:tbchlfdevpeer01pw@localhost:7054 --caname tally -M "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls" --enrollment.profile tls --csr.hosts tbchlfdevpeer01 --csr.hosts localhost --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/tlscacerts/"* "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/ca.crt"
  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/signcerts/"* "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/server.crt"
  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/keystore/"* "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/peers/tbchlfdevpeer01.tally.tallysolutions.comtls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname tally -M "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/users/User1@tally.tallysolutions.com/msp" --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/config.yaml" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/users/User1@tally.tallysolutions.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://tallyadmin:tallyadminpw@localhost:7054 --caname tally -M "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/users/Admin@tally.tallysolutions.com/msp" --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/tally/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/msp/config.yaml" "${HOME}/fabric/tally-network/organizations/peerOrganizations/tally.tallysolutions.com/users/Admin@tally.tallysolutions.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/tally.tallysolutions.com

  export FABRIC_CA_CLIENT_HOME=${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/msp/tlscacerts"
  cp "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/msp/tlscacerts/tlsca.tally.tallysolutions.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/tlsca"
  cp "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/tlsca/tlsca.tally.tallysolutions.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/msp" --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/msp/config.yaml" "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls" --enrollment.profile tls --csr.hosts orderer.tallysolutions.com --csr.hosts localhost --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/tlscacerts/"* "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/ca.crt"
  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/signcerts/"* "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/server.crt"
  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/keystore/"* "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/msp/tlscacerts"
  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/tls/tlscacerts/"* "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/orderers/orderer.tallysolutions.com/msp/tlscacerts/tlsca.tally.tallysolutions.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/users/Admin@tallysolutions.com/msp" --tls.certfiles "${HOME}/fabric/tally-network/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/msp/config.yaml" "${HOME}/fabric/tally-network/organizations/ordererOrganizations/tally.tallysolutions.com/users/Admin@tallysolutions.com/msp/config.yaml"
}
